database:
    driverClass: org.h2.Driver
    user: sa
    password: sa
    url: jdbc:h2:./target/dev

server:
    type: simple
    applicationContextPath: /
    connector:
        type: http
        port: 8080

logging:
    level: INFO
    loggers:
        com.csl456: DEBUG    
    
    appenders:
        - type: console
        - type: file
          currentLogFilename: './logs/application.log'
          archivedLogFilenamePattern: './logs/application-%d-%i.log.gz'
          archive: true
          archivedFileCount: 7
          maxFileSize: '1MiB'

smtpServerDetails:
    host: 'smtp.gmail.com'
    port: 25
    username: 'csl456bikerentalapp@gmail.com'
    password: 'igrcfuvlvvncbtfh'